# Generated by Django 2.0.2 on 2018-04-11 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_topic', models.IntegerField()),
                ('post_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_subject', models.CharField(max_length=255)),
                ('topic_date', models.DateTimeField()),
                ('topic_cat', models.IntegerField()),
                ('topic_by', models.IntegerField()),
                ('topic_deletion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Categories')),
                ('topic_user_deletion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
