# Generated by Django 2.0.2 on 2018-04-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255, unique=True)),
                ('cat_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_topic', models.IntegerField()),
                ('post_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('topic_subject', models.CharField(max_length=255)),
                ('topic_date', models.DateTimeField()),
                ('topic_cat', models.IntegerField()),
                ('topic_by', models.IntegerField()),
                ('topic_deletion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_date', models.DateTimeField()),
                ('user_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_user_deletion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.User'),
        ),
    ]
